package site.omagotchi.learningservice.study.infrastructure.persistence.entity;

public enum CommandResultCode {
    TIMER_STARTED,
    TIMER_STOPPED,
    TIMER_STOPPED_WITHOUT_RECORD,
    TIMER_DISCARDED,
    STUDY_RECORD_CREATED,
    STUDY_RECORD_UPDATED,
    STUDY_RECORD_DELETED,
    TIMER_ALREADY_RUNNING,
    TIMER_RUN_NOT_FOUND,
    TIMER_ALREADY_ENDED,
    STUDY_RECORD_NOT_FOUND,
    STUDY_RECORD_OVERLAP,
    STUDY_RECORD_VERSION_CONFLICT,
    STUDY_RECORD_POLICY_REJECTED
}
