CREATE TABLE learning_service.gamification_event_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(40) NOT NULL,
    source_id VARCHAR(100) NOT NULL,
    user_id UUID NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_gamification_event_receipts_source
        UNIQUE (event_type, source_id),
    CONSTRAINT ck_gamification_event_receipts_type
        CHECK (event_type IN ('ATTENDANCE_CHECKED_IN', 'STUDY_COMPLETED'))
);

CREATE INDEX ix_gamification_event_receipts_user_processed
    ON learning_service.gamification_event_receipts (user_id, processed_at DESC);
