CREATE TABLE learning_service.ranking_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_id BIGINT NOT NULL,
    period VARCHAR(20) NOT NULL,
    base_date DATE NOT NULL,
    range_start_date DATE NOT NULL,
    range_end_date DATE NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_ranking_snapshots_period
        UNIQUE (cohort_id, period, base_date),
    CONSTRAINT ck_ranking_snapshots_period
        CHECK (period IN ('DAILY', 'WEEKLY', 'MONTHLY')),
    CONSTRAINT ck_ranking_snapshots_range
        CHECK (range_start_date <= range_end_date)
);

CREATE TABLE learning_service.ranking_snapshot_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    user_character_id BIGINT NOT NULL,
    display_name VARCHAR(30) NOT NULL,
    study_seconds BIGINT NOT NULL,
    rank_position INTEGER NOT NULL,

    CONSTRAINT fk_ranking_snapshot_entries_snapshot
        FOREIGN KEY (snapshot_id)
        REFERENCES learning_service.ranking_snapshots (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ranking_snapshot_entries_user_character
        FOREIGN KEY (user_character_id)
        REFERENCES learning_service.user_characters (id),
    CONSTRAINT uq_ranking_snapshot_entries_character
        UNIQUE (snapshot_id, user_character_id),
    CONSTRAINT ck_ranking_snapshot_entries_display_name
        CHECK (display_name = BTRIM(display_name) AND char_length(display_name) BETWEEN 1 AND 30),
    CONSTRAINT ck_ranking_snapshot_entries_study_seconds
        CHECK (study_seconds > 0),
    CONSTRAINT ck_ranking_snapshot_entries_rank
        CHECK (rank_position > 0)
);

CREATE INDEX ix_ranking_snapshot_entries_snapshot_rank
    ON learning_service.ranking_snapshot_entries (snapshot_id, rank_position, study_seconds DESC);
