CREATE TABLE learning_service.gamification_event_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(40) NOT NULL,
    source_id VARCHAR(100) NOT NULL,
    user_id UUID NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error VARCHAR(1000),
    processed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_gamification_event_outbox_source
        UNIQUE (event_type, source_id),
    CONSTRAINT ck_gamification_event_outbox_type
        CHECK (event_type IN ('ATTENDANCE_CHECKED_IN', 'STUDY_COMPLETED')),
    CONSTRAINT ck_gamification_event_outbox_status
        CHECK (status IN ('PENDING', 'COMPLETED')),
    CONSTRAINT ck_gamification_event_outbox_attempt_count
        CHECK (attempt_count >= 0)
);

CREATE INDEX ix_gamification_event_outbox_retry
    ON learning_service.gamification_event_outbox (next_attempt_at, id)
    WHERE status = 'PENDING';
