CREATE TABLE learning_service.community_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    author_user_id UUID NOT NULL,
    scope VARCHAR(20) NOT NULL,
    cohort_id BIGINT,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT fk_community_posts_cohort
        FOREIGN KEY (cohort_id)
        REFERENCES learning_service.cohorts (id),
    CONSTRAINT ck_community_posts_type
        CHECK (type IN ('NOTICE', 'FREE')),
    CONSTRAINT ck_community_posts_scope
        CHECK (scope IN ('GLOBAL', 'COHORT')),
    CONSTRAINT ck_community_posts_scope_cohort
        CHECK (
            (scope = 'GLOBAL' AND cohort_id IS NULL)
            OR (scope = 'COHORT' AND cohort_id IS NOT NULL)
        ),
    CONSTRAINT ck_community_posts_title
        CHECK (title = BTRIM(title) AND char_length(title) BETWEEN 1 AND 100),
    CONSTRAINT ck_community_posts_content
        CHECK (char_length(BTRIM(content)) BETWEEN 1 AND 10000)
);

CREATE INDEX ix_community_posts_visible_list
    ON learning_service.community_posts (
        scope,
        cohort_id,
        type,
        pinned DESC,
        created_at DESC,
        id DESC
    )
    WHERE deleted_at IS NULL;

CREATE INDEX ix_community_posts_search
    ON learning_service.community_posts (created_at DESC, id DESC)
    WHERE deleted_at IS NULL;
