CREATE TABLE learning_service.community_post_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    storage_key VARCHAR(300) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_community_post_attachments_post
        FOREIGN KEY (post_id)
        REFERENCES learning_service.community_posts (id)
        ON DELETE CASCADE,
    CONSTRAINT uq_community_post_attachments_storage_key
        UNIQUE (storage_key),
    CONSTRAINT ck_community_post_attachments_storage_key
        CHECK (
            storage_key = BTRIM(storage_key)
            AND storage_key NOT LIKE '/%'
            AND storage_key NOT LIKE '%..%'
            AND char_length(storage_key) BETWEEN 1 AND 300
        ),
    CONSTRAINT ck_community_post_attachments_original_file_name
        CHECK (
            original_file_name = BTRIM(original_file_name)
            AND original_file_name NOT LIKE '%/%'
            AND original_file_name NOT LIKE '%\\%'
            AND original_file_name NOT LIKE '%..%'
            AND char_length(original_file_name) BETWEEN 1 AND 255
        ),
    CONSTRAINT ck_community_post_attachments_content_type
        CHECK (content_type IN ('image/jpeg', 'image/png', 'image/gif')),
    CONSTRAINT ck_community_post_attachments_size
        CHECK (size_bytes > 0),
    CONSTRAINT ck_community_post_attachments_display_order
        CHECK (display_order >= 0)
);

CREATE INDEX ix_community_post_attachments_post_order
    ON learning_service.community_post_attachments (post_id, display_order, id);
