-- User identifiers belong to identity-service and are referenced logically only.
CREATE TABLE learning_service.cohorts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PREPARING',
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT ck_cohorts_period CHECK (start_date <= end_date),
    CONSTRAINT ck_cohorts_status
        CHECK (status IN ('PREPARING', 'ACTIVE', 'CLOSED'))
);
