-- 센서 기기 마스터. device_eui 는 LoRaWAN 장치 식별자로 자연키다.
-- space_id 는 미배치 장비를 허용하므로 NULL 가능, 공간 삭제 시 SET NULL.
CREATE TABLE learning_service.sensor_devices (
     device_eui VARCHAR(32) PRIMARY KEY,
     space_id BIGINT,
     model VARCHAR(32) NOT NULL,
     display_name VARCHAR(64),
     installation_point VARCHAR(64),
     expected_interval_seconds INTEGER NOT NULL,
     active BOOLEAN NOT NULL DEFAULT TRUE,
     installed_at TIMESTAMPTZ,
     created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

     CONSTRAINT fk_sensor_devices_space
         FOREIGN KEY (space_id)
             REFERENCES learning_service.spaces (id)
             ON DELETE SET NULL,
     CONSTRAINT ck_sensor_devices_interval
         CHECK (expected_interval_seconds > 0)
);

CREATE INDEX ix_sensor_devices_space ON learning_service.sensor_devices (space_id);

-- 장치·측정 항목당 활성 룰은 하나다 (부분 유니크가 아니라 전체 유니크 — 소프트 삭제 없음).
-- Rule Engine 은 이 테이블에 직접 연결하지 않고 기동 시 REST 로 조회한 뒤
-- 인메모리 RuleCache 로만 운용하며, 변경은 RabbitMQ(rule.updated) 구독으로 갱신한다.
--
-- 장치 삭제 시 CASCADE 하지 않는다. 룰에 이력이 매달려 있어 캐스케이드가
-- 이력 FK 에 막히기 때문이며, 장치 회수는 active = FALSE 로 처리한다.
--
-- version 은 JPA 낙관적 락(@Version)이 관리한다. Hibernate 가 신규 행의 버전을
-- 0 으로 시드하므로 CHECK 는 1 이상이 아니라 0 이상이다.
CREATE TABLE learning_service.threshold_rules (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      device_eui VARCHAR(32) NOT NULL,
      metric VARCHAR(32) NOT NULL,
      operator VARCHAR(8) NOT NULL,
      threshold DOUBLE PRECISION NOT NULL,
      version BIGINT NOT NULL DEFAULT 0,
      created_by_user_id UUID,
      updated_by_user_id UUID,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_threshold_rules_device
          FOREIGN KEY (device_eui)
              REFERENCES learning_service.sensor_devices (device_eui),
      CONSTRAINT uq_threshold_rules_device_metric
          UNIQUE (device_eui, metric),
      -- Rule Engine 이 SensorReading.measurement 와 문자열 완전 일치로 매칭하므로
      -- 대소문자·공백이 섞이면 룰이 조용히 미적중한다. 저장 시점에 원천 차단한다.
      CONSTRAINT ck_threshold_rules_metric
          CHECK (metric = LOWER(BTRIM(metric)) AND metric <> ''),
      CONSTRAINT ck_threshold_rules_operator
          CHECK (operator IN ('GT', 'GTE', 'LT', 'LTE')),
      CONSTRAINT ck_threshold_rules_version
          CHECK (version >= 0)
);

-- 룰 변경 이력. append-only 이므로 (rule_id, rule_version) 이 유일하다.
-- previous_operator / previous_threshold 는 의도적으로 두지 않는다 —
-- 직전 rule_version 행의 next_* 에서 파생 가능한 중복이라 필요 시 LAG 로 조회한다.
--
-- version 갱신과 이 테이블의 INSERT 는 반드시 같은 트랜잭션으로 묶는다.
-- 트리거를 쓰지 않으므로 이 정합성은 전적으로 애플리케이션 코드 책임이다.
CREATE TABLE learning_service.threshold_rule_histories (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       rule_id BIGINT NOT NULL,
       rule_version BIGINT NOT NULL,
       change_type VARCHAR(20) NOT NULL,
       next_operator VARCHAR(8) NOT NULL,
       next_threshold DOUBLE PRECISION NOT NULL,
       changed_by_user_id UUID,
       request_id VARCHAR(100),
       changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

       -- 룰 삭제 경로가 없으므로 CASCADE 하지 않는다.
       -- 이력이 남아 있는 룰의 삭제를 이 FK 가 그대로 막아준다.
       CONSTRAINT fk_threshold_rule_history_rule
           FOREIGN KEY (rule_id)
               REFERENCES learning_service.threshold_rules (id),
       CONSTRAINT ck_threshold_rule_history_change_type
           CHECK (change_type IN ('CREATED', 'UPDATED')),
       -- threshold_rules.version 과 같은 시드(0)를 공유한다.
       CONSTRAINT ck_threshold_rule_history_version
           CHECK (rule_version >= 0),
       CONSTRAINT ck_threshold_rule_history_next_operator
           CHECK (next_operator IN ('GT', 'GTE', 'LT', 'LTE')),
       -- 버전당 이력 행이 정확히 하나만 존재하도록 보장한다.
       CONSTRAINT uq_threshold_rule_history_version
           UNIQUE (rule_id, rule_version)
);

-- "이 룰의 최근 변경 이력부터 조회" 패턴 최적화.
CREATE INDEX idx_threshold_rule_history_time
    ON learning_service.threshold_rule_histories (rule_id, changed_at DESC);
