CREATE TABLE learning_service.cohort_attendance_policies (
    cohort_id BIGINT PRIMARY KEY,
    timezone VARCHAR(50) NOT NULL DEFAULT 'Asia/Seoul',
    scheduled_start_time TIME NOT NULL,
    scheduled_end_time TIME NOT NULL,
    absence_cutoff_time TIME,
    allowed_away_minutes INTEGER NOT NULL DEFAULT 0,
    updated_by_user_id BIGINT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_cohort_attendance_policies_cohort
        FOREIGN KEY (cohort_id)
        REFERENCES learning_service.cohorts (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_cohort_attendance_policies_schedule
        CHECK (scheduled_start_time < scheduled_end_time),
    CONSTRAINT ck_cohort_attendance_policies_allowed_away
        CHECK (allowed_away_minutes >= 0)
);

CREATE TABLE learning_service.cohort_join_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_id BIGINT NOT NULL,
    code_hash VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    expires_at TIMESTAMPTZ NOT NULL,
    issued_by_user_id BIGINT NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMPTZ,

    CONSTRAINT fk_cohort_join_codes_cohort
        FOREIGN KEY (cohort_id)
        REFERENCES learning_service.cohorts (id)
        ON DELETE CASCADE,
    CONSTRAINT uq_cohort_join_codes_code_hash UNIQUE (code_hash),
    CONSTRAINT ck_cohort_join_codes_code_hash_length
        CHECK (char_length(code_hash) = 64),
    CONSTRAINT ck_cohort_join_codes_status
        CHECK (status IN ('ACTIVE', 'REVOKED')),
    CONSTRAINT ck_cohort_join_codes_revoked_at
        CHECK (
            (status = 'REVOKED' AND revoked_at IS NOT NULL)
            OR (status = 'ACTIVE' AND revoked_at IS NULL)
        )
);

CREATE UNIQUE INDEX uq_cohort_join_codes_active_cohort
    ON learning_service.cohort_join_codes (cohort_id)
    WHERE status = 'ACTIVE';

CREATE TABLE learning_service.cohort_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'STUDENT',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ,
    processed_by_user_id BIGINT,
    rejection_reason VARCHAR(500),
    ended_at TIMESTAMPTZ,

    CONSTRAINT fk_cohort_memberships_cohort
        FOREIGN KEY (cohort_id)
        REFERENCES learning_service.cohorts (id)
        ON DELETE CASCADE,
    CONSTRAINT uq_cohort_memberships_cohort_user UNIQUE (cohort_id, user_id),
    CONSTRAINT ck_cohort_memberships_role
        CHECK (role IN ('STUDENT', 'MENTOR', 'MANAGER')),
    CONSTRAINT ck_cohort_memberships_status
        CHECK (status IN ('PENDING', 'ACTIVE', 'REJECTED', 'ENDED')),
    CONSTRAINT ck_cohort_memberships_processed
        CHECK (
            (status = 'PENDING' AND processed_at IS NULL AND processed_by_user_id IS NULL)
            OR (status <> 'PENDING' AND processed_at IS NOT NULL AND processed_by_user_id IS NOT NULL)
        ),
    CONSTRAINT ck_cohort_memberships_rejection_reason
        CHECK (
            (status = 'REJECTED' AND rejection_reason IS NOT NULL)
            OR (status <> 'REJECTED')
        ),
    CONSTRAINT ck_cohort_memberships_ended_at
        CHECK (
            (status = 'ENDED' AND ended_at IS NOT NULL)
            OR (status <> 'ENDED')
        )
);

CREATE UNIQUE INDEX uq_cohort_memberships_active_student
    ON learning_service.cohort_memberships (user_id)
    WHERE role = 'STUDENT'
      AND status = 'ACTIVE'
      AND ended_at IS NULL;

CREATE INDEX ix_cohort_memberships_cohort_status_requested
    ON learning_service.cohort_memberships (cohort_id, status, requested_at);

CREATE INDEX ix_cohort_memberships_user_requested
    ON learning_service.cohort_memberships (user_id, requested_at DESC);

CREATE TABLE learning_service.cohort_audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_id BIGINT NOT NULL,
    actor_user_id BIGINT NOT NULL,
    target_type VARCHAR(30) NOT NULL,
    target_id BIGINT,
    action VARCHAR(50) NOT NULL,
    before_value JSONB,
    after_value JSONB,
    reason VARCHAR(500),
    request_id VARCHAR(100) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_cohort_audit_logs_cohort
        FOREIGN KEY (cohort_id)
        REFERENCES learning_service.cohorts (id)
        ON DELETE CASCADE
);

CREATE INDEX ix_cohort_audit_logs_cohort_occurred
    ON learning_service.cohort_audit_logs (cohort_id, occurred_at DESC);

CREATE INDEX ix_cohort_audit_logs_target
    ON learning_service.cohort_audit_logs (target_type, target_id);
