-- 공간·회의실·팀 도메인 테이블 생성 (ERD v3)
--
-- 선행 조건: learning_service.cohort_memberships 에 UNIQUE (id, user_id) 가 필요하다.
--            점유·참여의 복합 FK 참조점이며 기수 파트에 추가를 요청한 상태다.
--            id 가 PK이므로 이 UNIQUE 는 어떤 행도 새로 막지 않는다(순수 참조점).
DO $$
BEGIN
    IF to_regclass('learning_service.cohort_memberships') IS NULL THEN
        RAISE EXCEPTION '선행 조건 미충족: learning_service.cohort_memberships 가 없습니다. 기수 파트 마이그레이션을 먼저 적용하세요.';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        WHERE c.conrelid = 'learning_service.cohort_memberships'::regclass
          AND c.contype IN ('p', 'u')
          AND (
              SELECT array_agg(a.attname::text ORDER BY a.attname)
              FROM unnest(c.conkey) AS k
              JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k
          ) = ARRAY['id', 'user_id']
    ) THEN
        RAISE EXCEPTION '선행 조건 미충족: cohort_memberships (id, user_id) UNIQUE 가 없습니다. 기수 파트에 uq_cohort_memberships_id_user 추가를 요청하세요.';
    END IF;
END
$$;

-- 물리 공간 마스터. 출석·센서가 FK로 참조하는 정본이다.
-- cohort_id 는 소속이 아니라 "관리 주체 기수"이므로 기수 삭제 시 SET NULL 이다.
-- status DEFAULT 는 의도적으로 INACTIVE 다 (RM-10, 생성 시 기본 비활성).
CREATE TABLE learning_service.spaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    space_type VARCHAR(20) NOT NULL,
    cohort_id BIGINT,
    capacity INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL DEFAULT 'INACTIVE',
    inactive_reason VARCHAR(200),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT fk_spaces_cohort
        FOREIGN KEY (cohort_id)
            REFERENCES learning_service.cohorts (id)
            ON DELETE SET NULL,
    CONSTRAINT ck_spaces_name
        CHECK (name = BTRIM(name) AND char_length(name) BETWEEN 1 AND 50),
    CONSTRAINT ck_spaces_space_type
        CHECK (space_type IN ('LAB', 'MEETING', 'STUDY')),
    CONSTRAINT ck_spaces_capacity
        CHECK (capacity > 0),
    CONSTRAINT ck_spaces_status
        CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_spaces_inactive_reason
        CHECK (status = 'INACTIVE' OR inactive_reason IS NULL)
);

-- 회의실 점유 세션(사건·이력). 종료 후에도 행을 보존한다.
-- cohort_id 와 team_id 가 없는 것은 의도다 (v3) — 기수는 occupier_membership_id
-- 조인으로 도출하고, 점유는 항상 개인 단위라 팀 태그를 두지 않는다 (MR-11).
-- 복합 FK 하나로 멤버십 실재와 membership-user 소유 일치를 함께 보장한다.
CREATE TABLE learning_service.room_occupancies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id BIGINT NOT NULL,
    occupier_membership_id BIGINT NOT NULL,
    occupier_user_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    extension_count SMALLINT NOT NULL DEFAULT 0,
    reminder_sent_at TIMESTAMPTZ,

    CONSTRAINT fk_room_occupancies_space
        FOREIGN KEY (space_id)
            REFERENCES learning_service.spaces (id),
    CONSTRAINT fk_room_occupancies_occupier
        FOREIGN KEY (occupier_membership_id, occupier_user_id)
            REFERENCES learning_service.cohort_memberships (id, user_id),
    CONSTRAINT ck_room_occupancies_status
        CHECK (status IN ('ACTIVE', 'RELEASED', 'EXPIRED', 'FORCE_RELEASED')),
    CONSTRAINT ck_room_occupancies_period
        CHECK (expires_at > started_at),
    CONSTRAINT ck_room_occupancies_extension_count
        CHECK (extension_count BETWEEN 0 AND 2),
    CONSTRAINT ck_room_occupancies_end
        CHECK ((status = 'ACTIVE') = (ended_at IS NULL)),
    CONSTRAINT ck_room_occupancies_ended_period
        CHECK (ended_at IS NULL OR ended_at >= started_at)
);

-- 점유 세션의 참여자. left_at 구간 모델 — NULL=참여 중, 값=이탈·제외·종료 시각.
-- 재합류는 새 행이 아니라 기존 행의 left_at 을 NULL 로 되돌린다 (결정 #30).
CREATE TABLE learning_service.occupancy_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occupancy_id BIGINT NOT NULL,
    cohort_membership_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMPTZ,

    CONSTRAINT fk_occupancy_participants_occupancy
        FOREIGN KEY (occupancy_id)
            REFERENCES learning_service.room_occupancies (id),
    CONSTRAINT fk_occupancy_participants_member
        FOREIGN KEY (cohort_membership_id, user_id)
            REFERENCES learning_service.cohort_memberships (id, user_id),
    CONSTRAINT ck_occupancy_participants_period
        CHECK (left_at IS NULL OR left_at >= joined_at)
);

-- 공실 알림 신청(일회성 의사표시). 소진은 notified_at, 취소·정리는 물리 삭제.
-- user_id 가 없는 것은 의도다 (v3) — 물리적 배타가 아니라 기수 스코프 의사표시라
-- 멤버십 기준이며, 다기수 담당자는 멤버십 수만큼 알림을 받는다.
CREATE TABLE learning_service.vacancy_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id BIGINT NOT NULL,
    cohort_membership_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notified_at TIMESTAMPTZ,

    CONSTRAINT fk_vacancy_alerts_space
        FOREIGN KEY (space_id)
            REFERENCES learning_service.spaces (id),
    CONSTRAINT fk_vacancy_alerts_membership
        FOREIGN KEY (cohort_membership_id)
            REFERENCES learning_service.cohort_memberships (id)
            ON DELETE CASCADE,
    CONSTRAINT ck_vacancy_alerts_notified
        CHECK (notified_at IS NULL OR notified_at >= created_at)
);

-- 랭킹·게이미피케이션의 사회적 단위(기수 스코프). 공간 접근과 무관하다.
-- updated_at 과 생성자 컬럼이 없는 것은 의도다 — 팀 수정 기능이 없고,
-- 권한 판정은 team_members.role, 자동 위임은 joined_at 기준이라 생성자가 쓰이지 않는다.
CREATE TABLE learning_service.teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_id BIGINT NOT NULL,
    name VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT fk_teams_cohort
        FOREIGN KEY (cohort_id)
            REFERENCES learning_service.cohorts (id)
            ON DELETE CASCADE,
    CONSTRAINT ck_teams_name
        CHECK (name = BTRIM(name) AND char_length(name) BETWEEN 1 AND 30)
);

-- 팀 소속. 행 존재 = 소속이므로 상태 컬럼이 없고, 탈퇴·제외·해체 시 물리 삭제한다.
-- cohort_id 가 없는 것은 의도다 (v3) — 팀의 기수와 일치 여부는 앱 검증이다 (GR-22).
CREATE TABLE learning_service.team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    cohort_membership_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_team_members_team
        FOREIGN KEY (team_id)
            REFERENCES learning_service.teams (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_team_members_membership
        FOREIGN KEY (cohort_membership_id)
            REFERENCES learning_service.cohort_memberships (id)
            ON DELETE CASCADE,
    CONSTRAINT ck_team_members_role
        CHECK (role IN ('MASTER', 'MEMBER'))
);

-- 공간·회의실·팀 도메인 부분 유니크·함수 인덱스 (ERD v3 3장)
--
-- WHERE 절이 붙는 유니크는 테이블 제약으로 표현할 수 없어 전부 인덱스로 만든다.
-- 따라서 애플리케이션에서 잡히는 예외는 제약 위반이 아니라 인덱스 위반이며,
-- 409 변환 시 인덱스명으로 분기해야 한다.

CREATE UNIQUE INDEX uq_spaces_active_name
    ON learning_service.spaces (LOWER(BTRIM(name)))
    WHERE deleted_at IS NULL;

-- 유니크가 아닌 것은 의도다 — 한 기수에 실습실을 여러 개 배정할 수 있다 (RM-26).
-- 그 대가로 동시 배정 방지는 spaces 행 락이 유일한 방어선이다.
CREATE INDEX ix_spaces_lab_cohort
    ON learning_service.spaces (cohort_id)
    WHERE space_type = 'LAB' AND deleted_at IS NULL;

-- 해체된 팀은 제외한다 — 동명 재생성을 허용해야 하므로 (GR-19).
CREATE UNIQUE INDEX uq_teams_active_name
    ON learning_service.teams (cohort_id, LOWER(BTRIM(name)))
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uq_team_members_membership
    ON learning_service.team_members (cohort_membership_id);

-- 유니크 자체는 위 인덱스에 포함되지만 team_id 선두라 팀원 목록·정원 카운트
-- 조회 경로를 겸한다. 잉여로 보여도 삭제 금지.
CREATE UNIQUE INDEX uq_team_members_team_membership
    ON learning_service.team_members (team_id, cohort_membership_id);

-- 팀당 MASTER 최대 1명. 최소 1명은 DB로 표현할 수 없어 트랜잭션 책임이다 (GR-12).
CREATE UNIQUE INDEX uq_team_members_one_master
    ON learning_service.team_members (team_id)
    WHERE role = 'MASTER';

CREATE UNIQUE INDEX uq_room_occupancies_one_active_per_space
    ON learning_service.room_occupancies (space_id)
    WHERE status = 'ACTIVE';

-- 멤버십이 아니라 계정 기준이다 — 다기수 담당자도 방 2개를 잡을 수 없다 (MR-10).
CREATE UNIQUE INDEX uq_room_occupancies_one_active_per_user
    ON learning_service.room_occupancies (occupier_user_id)
    WHERE status = 'ACTIVE';

CREATE INDEX ix_room_occupancies_expiration
    ON learning_service.room_occupancies (expires_at)
    WHERE status = 'ACTIVE';

CREATE UNIQUE INDEX uq_occupancy_participants_pair
    ON learning_service.occupancy_participants (occupancy_id, user_id);

CREATE UNIQUE INDEX uq_occupancy_participants_one_active
    ON learning_service.occupancy_participants (user_id)
    WHERE left_at IS NULL;

CREATE UNIQUE INDEX uq_vacancy_alerts_waiting
    ON learning_service.vacancy_alerts (space_id, cohort_membership_id)
    WHERE notified_at IS NULL;

-- 공간 시드
--
-- spaces.status 의 DEFAULT 는 INACTIVE 다 (RM-10). status 를 명시하지 않으면
-- 배포 직후 모든 공간이 점유·재실 신청을 받지 못하므로 전부 ACTIVE 를 지정한다.
--
-- cohort_id = NULL 인 시드 공간은 관리 주체 기수가 없어 삭제 주체도 없다 (RM-25).
-- 삭제 차단은 DB 제약이 아니라 삭제 API 의 책임이다.
-- LAB 은 미배정 상태로 시작하고 실제 배정은 실습실 배정 API 가 수행한다 (RM-24).
--
-- TODO(운영): 아래 목록은 예시다. 실제 원하는 시설 명칭·수량·정원으로 교체할 것.

INSERT INTO learning_service.spaces (name, space_type, cohort_id, capacity, status)
VALUES
    ('1실습실', 'LAB', NULL, 30, 'ACTIVE'),
    ('2실습실', 'LAB', NULL, 30, 'ACTIVE'),
    ('3실습실', 'LAB', NULL, 30, 'ACTIVE'),
    ('1회의실', 'MEETING', NULL, 6, 'ACTIVE'),
    ('2회의실', 'MEETING', NULL, 6, 'ACTIVE'),
    ('3회의실', 'MEETING', NULL, 4, 'ACTIVE'),
    ('4회의실', 'MEETING', NULL, 4, 'ACTIVE'),
    ('1독서실', 'STUDY', NULL, 20, 'ACTIVE'),
    ('2독서실', 'STUDY', NULL, 20, 'ACTIVE')
    ON CONFLICT DO NOTHING;

-- 위 함정을 배포 시점에 잡기 위한 안전망이다.
DO $$
DECLARE
    active_total INTEGER;
    active_meeting INTEGER;
BEGIN
    SELECT count(*) INTO active_total
    FROM learning_service.spaces
    WHERE status = 'ACTIVE' AND deleted_at IS NULL;

    SELECT count(*) INTO active_meeting
    FROM learning_service.spaces
    WHERE status = 'ACTIVE' AND deleted_at IS NULL AND space_type = 'MEETING';

    IF active_total = 0 THEN
        RAISE EXCEPTION '시드 검증 실패: 활성 공간이 0개입니다. spaces.status DEFAULT 가 INACTIVE 이므로 시드에서 ACTIVE 를 명시했는지 확인하세요.';
    END IF;

    IF active_meeting = 0 THEN
        RAISE EXCEPTION '시드 검증 실패: 활성 회의실이 0개입니다. 점유 기능이 동작할 수 없습니다.';
    END IF;
END
$$;
