CREATE TABLE learning_service.telegram_user_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    telegram_user_id BIGINT NOT NULL,
    telegram_chat_id BIGINT NOT NULL,
    notification_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    linked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    disconnected_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_telegram_user_links_user UNIQUE (user_id),
    CONSTRAINT uq_telegram_user_links_telegram_user UNIQUE (telegram_user_id),
    CONSTRAINT uq_telegram_user_links_chat UNIQUE (telegram_chat_id),
    CONSTRAINT ck_telegram_user_links_disconnected
        CHECK (
            disconnected_at IS NULL
            OR disconnected_at >= linked_at
        )
);

CREATE INDEX ix_telegram_user_links_notification_enabled
    ON learning_service.telegram_user_links (notification_enabled);

CREATE TABLE learning_service.telegram_link_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_telegram_link_tokens_hash UNIQUE (token_hash),
    CONSTRAINT ck_telegram_link_tokens_used_at
        CHECK (
            used_at IS NULL
            OR used_at >= created_at
        ),
    CONSTRAINT ck_telegram_link_tokens_expires_at
        CHECK (expires_at > created_at)
);

CREATE INDEX ix_telegram_link_tokens_user
    ON learning_service.telegram_link_tokens (user_id);

CREATE INDEX ix_telegram_link_tokens_expires_at
    ON learning_service.telegram_link_tokens (expires_at);

CREATE TABLE learning_service.attendance_reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_membership_id BIGINT NOT NULL,
    attendance_date DATE NOT NULL,
    reminder_type VARCHAR(40) NOT NULL,
    channel VARCHAR(20) NOT NULL DEFAULT 'TELEGRAM',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    sent_at TIMESTAMPTZ,
    confirmed_at TIMESTAMPTZ,
    telegram_message_id BIGINT,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_attendance_reminders_membership
        FOREIGN KEY (cohort_membership_id)
        REFERENCES learning_service.cohort_memberships (id)
        ON DELETE CASCADE,
    CONSTRAINT uq_attendance_reminders_once
        UNIQUE (cohort_membership_id, attendance_date, reminder_type, channel),
    CONSTRAINT ck_attendance_reminders_type
        CHECK (reminder_type IN (
            'CHECK_IN_BEFORE_DEADLINE',
            'CHECK_OUT_BEFORE_DEADLINE'
        )),
    CONSTRAINT ck_attendance_reminders_channel
        CHECK (channel IN ('TELEGRAM')),
    CONSTRAINT ck_attendance_reminders_status
        CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'SKIPPED')),
    CONSTRAINT ck_attendance_reminders_attempt_count
        CHECK (attempt_count >= 0)
);

CREATE INDEX ix_attendance_reminders_membership_date
    ON learning_service.attendance_reminders (cohort_membership_id, attendance_date);

CREATE INDEX ix_attendance_reminders_status
    ON learning_service.attendance_reminders (status);

CREATE INDEX ix_attendance_reminders_sent_at
    ON learning_service.attendance_reminders (sent_at);
