CREATE TABLE learning_service.attendance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_membership_id BIGINT NOT NULL,
    attendance_date DATE NOT NULL,
    checked_in_at TIMESTAMPTZ,
    checked_out_at TIMESTAMPTZ,
    auto_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    final_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    late_minutes INTEGER NOT NULL DEFAULT 0,
    early_leave_minutes INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_attendance_records_membership
        FOREIGN KEY (cohort_membership_id)
        REFERENCES learning_service.cohort_memberships (id)
        ON DELETE CASCADE,
    CONSTRAINT uq_attendance_records_membership_date
        UNIQUE (cohort_membership_id, attendance_date),
    CONSTRAINT ck_attendance_records_auto_status
        CHECK (auto_status IN (
            'PENDING',
            'PRESENT',
            'LATE',
            'ABSENT',
            'LEFT_EARLY',
            'MISSING_CHECK_OUT'
        )),
    CONSTRAINT ck_attendance_records_final_status
        CHECK (final_status IN (
            'PENDING',
            'PRESENT',
            'LATE',
            'ABSENT',
            'LEFT_EARLY',
            'MISSING_CHECK_OUT'
        )),
    CONSTRAINT ck_attendance_records_checkout
        CHECK (
            checked_out_at IS NULL
            OR checked_in_at IS NULL
            OR checked_out_at >= checked_in_at
        ),
    CONSTRAINT ck_attendance_records_late_minutes
        CHECK (late_minutes >= 0),
    CONSTRAINT ck_attendance_records_early_leave_minutes
        CHECK (early_leave_minutes >= 0),
    CONSTRAINT ck_attendance_records_version
        CHECK (version >= 0)
);

CREATE INDEX ix_attendance_records_membership_date
    ON learning_service.attendance_records (cohort_membership_id, attendance_date DESC);

CREATE INDEX ix_attendance_records_date_status
    ON learning_service.attendance_records (attendance_date, final_status);

CREATE TABLE learning_service.presence_intervals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_id BIGINT NOT NULL,
    state VARCHAR(20) NOT NULL,
    space_id BIGINT,
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_presence_intervals_attendance
        FOREIGN KEY (attendance_id)
        REFERENCES learning_service.attendance_records (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_presence_intervals_state
        CHECK (state IN ('PRESENT', 'AWAY', 'MEETING', 'STUDYING')),
    CONSTRAINT ck_presence_intervals_time
        CHECK (
            ended_at IS NULL
            OR ended_at >= started_at
        )
);

CREATE INDEX ix_presence_intervals_attendance
    ON learning_service.presence_intervals (attendance_id, started_at);

CREATE TABLE learning_service.attendance_change_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_id BIGINT NOT NULL,
    actor_user_id UUID NOT NULL,
    previous_status VARCHAR(20) NOT NULL,
    next_status VARCHAR(20) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    request_id VARCHAR(100) NOT NULL,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_attendance_change_logs_attendance
        FOREIGN KEY (attendance_id)
        REFERENCES learning_service.attendance_records (id)
        ON DELETE CASCADE,
    CONSTRAINT ck_attendance_change_logs_previous_status
        CHECK (previous_status IN (
            'PENDING',
            'PRESENT',
            'LATE',
            'ABSENT',
            'LEFT_EARLY',
            'MISSING_CHECK_OUT'
        )),
    CONSTRAINT ck_attendance_change_logs_next_status
        CHECK (next_status IN (
            'PENDING',
            'PRESENT',
            'LATE',
            'ABSENT',
            'LEFT_EARLY',
            'MISSING_CHECK_OUT'
        ))
);

CREATE INDEX ix_attendance_change_logs_attendance
    ON learning_service.attendance_change_logs (attendance_id, changed_at DESC);
