-- 공간·회의실·팀 도메인 테이블 생성 (ERD v3)
--
-- 선행 조건: learning_service.cohort_memberships 에 UNIQUE (id, user_id) 가 필요하다.
--            점유·참여의 복합 FK 참조점이며 기수 파트에 추가를 요청한 상태다.
--            id 가 PK이므로 이 UNIQUE 는 어떤 행도 새로 막지 않는다(순수 참조점).
DO $$
BEGIN
    IF to_regclass('learning_service.cohort_memberships') IS NULL THEN
        RAISE EXCEPTION '선행 조건 미충족: learning_service.cohort_memberships 가 없습니다. 기수 파트 마이그레이션을 먼저 적용하세요.';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        WHERE c.conrelid = 'learning_service.cohort_memberships'::regclass
          AND c.contype IN ('p', 'u')
          AND (
              SELECT array_agg(a.attname ORDER BY a.attname)
              FROM unnest(c.conkey) AS k
              JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k
          ) = ARRAY['id', 'user_id']
    ) THEN
        RAISE EXCEPTION '선행 조건 미충족: cohort_memberships (id, user_id) UNIQUE 가 없습니다. 기수 파트에 uq_cohort_memberships_id_user 추가를 요청하세요.';
    END IF;
END
$$;

-- 물리 공간 마스터. 출석·센서가 FK로 참조하는 정본이다.
-- cohort_id 는 소속이 아니라 "관리 주체 기수"이므로 기수 삭제 시 SET NULL 이다.
-- status DEFAULT 는 의도적으로 INACTIVE 다 (RM-10, 생성 시 기본 비활성).
CREATE TABLE learning_service.spaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    space_type VARCHAR(20) NOT NULL,
    cohort_id BIGINT,
    capacity INTEGER NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL DEFAULT 'INACTIVE',
    inactive_reason VARCHAR(200),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT fk_spaces_cohort
        FOREIGN KEY (cohort_id)
            REFERENCES learning_service.cohorts (id)
            ON DELETE SET NULL,
    CONSTRAINT ck_spaces_name
        CHECK (name = BTRIM(name) AND char_length(name) BETWEEN 1 AND 50),
    CONSTRAINT ck_spaces_space_type
        CHECK (space_type IN ('LAB', 'MEETING', 'STUDY')),
    CONSTRAINT ck_spaces_capacity
        CHECK (capacity > 0),
    CONSTRAINT ck_spaces_status
        CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_spaces_inactive_reason
        CHECK (status = 'INACTIVE' OR inactive_reason IS NULL)
);

-- 회의실 점유 세션(사건·이력). 종료 후에도 행을 보존한다.
-- cohort_id 와 team_id 가 없는 것은 의도다 (v3) — 기수는 occupier_membership_id
-- 조인으로 도출하고, 점유는 항상 개인 단위라 팀 태그를 두지 않는다 (MR-11).
-- 복합 FK 하나로 멤버십 실재와 membership-user 소유 일치를 함께 보장한다.
CREATE TABLE learning_service.room_occupancies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id BIGINT NOT NULL,
    occupier_membership_id BIGINT NOT NULL,
    occupier_user_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    extension_count SMALLINT NOT NULL DEFAULT 0,
    reminder_sent_at TIMESTAMPTZ,

    CONSTRAINT fk_room_occupancies_space
        FOREIGN KEY (space_id)
            REFERENCES learning_service.spaces (id),
    CONSTRAINT fk_room_occupancies_occupier
        FOREIGN KEY (occupier_membership_id, occupier_user_id)
            REFERENCES learning_service.cohort_memberships (id, user_id),
    CONSTRAINT ck_room_occupancies_status
        CHECK (status IN ('ACTIVE', 'RELEASED', 'EXPIRED', 'FORCE_RELEASED')),
    CONSTRAINT ck_room_occupancies_period
        CHECK (expires_at > started_at),
    CONSTRAINT ck_room_occupancies_extension_count
        CHECK (extension_count BETWEEN 0 AND 2),
    CONSTRAINT ck_room_occupancies_end
        CHECK ((status = 'ACTIVE') = (ended_at IS NULL)),
    CONSTRAINT ck_room_occupancies_ended_period
        CHECK (ended_at IS NULL OR ended_at >= started_at)
);

-- 점유 세션의 참여자. left_at 구간 모델 — NULL=참여 중, 값=이탈·제외·종료 시각.
-- 재합류는 새 행이 아니라 기존 행의 left_at 을 NULL 로 되돌린다 (결정 #30).
CREATE TABLE learning_service.occupancy_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occupancy_id BIGINT NOT NULL,
    cohort_membership_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMPTZ,

    CONSTRAINT fk_occupancy_participants_occupancy
        FOREIGN KEY (occupancy_id)
            REFERENCES learning_service.room_occupancies (id),
    CONSTRAINT fk_occupancy_participants_member
        FOREIGN KEY (cohort_membership_id, user_id)
            REFERENCES learning_service.cohort_memberships (id, user_id),
    CONSTRAINT ck_occupancy_participants_period
        CHECK (left_at IS NULL OR left_at >= joined_at)
);

-- 공실 알림 신청(일회성 의사표시). 소진은 notified_at, 취소·정리는 물리 삭제.
-- user_id 가 없는 것은 의도다 (v3) — 물리적 배타가 아니라 기수 스코프 의사표시라
-- 멤버십 기준이며, 다기수 담당자는 멤버십 수만큼 알림을 받는다.
CREATE TABLE learning_service.vacancy_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id BIGINT NOT NULL,
    cohort_membership_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notified_at TIMESTAMPTZ,

    CONSTRAINT fk_vacancy_alerts_space
        FOREIGN KEY (space_id)
            REFERENCES learning_service.spaces (id),
    CONSTRAINT fk_vacancy_alerts_membership
        FOREIGN KEY (cohort_membership_id)
            REFERENCES learning_service.cohort_memberships (id)
            ON DELETE CASCADE,
    CONSTRAINT ck_vacancy_alerts_notified
        CHECK (notified_at IS NULL OR notified_at >= created_at)
);

-- 랭킹·게이미피케이션의 사회적 단위(기수 스코프). 공간 접근과 무관하다.
-- updated_at 과 생성자 컬럼이 없는 것은 의도다 — 팀 수정 기능이 없고,
-- 권한 판정은 team_members.role, 자동 위임은 joined_at 기준이라 생성자가 쓰이지 않는다.
CREATE TABLE learning_service.teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_id BIGINT NOT NULL,
    name VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT fk_teams_cohort
        FOREIGN KEY (cohort_id)
            REFERENCES learning_service.cohorts (id)
            ON DELETE CASCADE,
    CONSTRAINT ck_teams_name
        CHECK (name = BTRIM(name) AND char_length(name) BETWEEN 1 AND 30)
);

-- 팀 소속. 행 존재 = 소속이므로 상태 컬럼이 없고, 탈퇴·제외·해체 시 물리 삭제한다.
-- cohort_id 가 없는 것은 의도다 (v3) — 팀의 기수와 일치 여부는 앱 검증이다 (GR-22).
CREATE TABLE learning_service.team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    cohort_membership_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_team_members_team
        FOREIGN KEY (team_id)
            REFERENCES learning_service.teams (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_team_members_membership
        FOREIGN KEY (cohort_membership_id)
            REFERENCES learning_service.cohort_memberships (id)
            ON DELETE CASCADE,
    CONSTRAINT ck_team_members_role
        CHECK (role IN ('MASTER', 'MEMBER'))
);