CREATE TABLE learning_service.game_characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    code VARCHAR(30) NOT NULL,
    description VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_game_characters_code UNIQUE (code),
    CONSTRAINT ck_game_characters_code
        CHECK (code = upper(btrim(code)) AND char_length(code) BETWEEN 1 AND 30),
    CONSTRAINT ck_game_characters_name
        CHECK (name = btrim(name) AND char_length(name) BETWEEN 1 AND 50),
    CONSTRAINT ck_game_characters_description
        CHECK (description IS NULL OR char_length(description) <= 255)
);

CREATE TABLE learning_service.user_characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    game_character_id BIGINT NOT NULL,
    nickname VARCHAR(30) NOT NULL,
    is_representative BOOLEAN NOT NULL DEFAULT FALSE,
    total_xp BIGINT NOT NULL DEFAULT 0,
    level INTEGER NOT NULL DEFAULT 1,
    advancement_stage VARCHAR(20) NOT NULL DEFAULT 'BASE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version SMALLINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_user_characters_game_character
        FOREIGN KEY (game_character_id)
        REFERENCES learning_service.game_characters (id),
    CONSTRAINT ck_user_characters_nickname
        CHECK (nickname = BTRIM(nickname) AND char_length(nickname) BETWEEN 1 AND 30),
    CONSTRAINT ck_user_characters_xp
        CHECK (total_xp >= 0),
    CONSTRAINT ck_user_characters_level
        CHECK (level BETWEEN 1 AND 30),
    CONSTRAINT ck_user_characters_advancement_stage
        CHECK (advancement_stage IN ('BASE', 'FIRST', 'SECOND', 'THIRD')),
    CONSTRAINT ck_user_characters_version
        CHECK (version >= 0)
);

CREATE UNIQUE INDEX uq_user_characters_representative
    ON learning_service.user_characters (user_id)
    WHERE is_representative;

CREATE INDEX ix_user_characters_game_character
    ON learning_service.user_characters (game_character_id);

CREATE TABLE learning_service.level_policies (
    level INTEGER PRIMARY KEY,
    min_total_xp BIGINT NOT NULL,

    CONSTRAINT ck_level_policies_level
        CHECK (level BETWEEN 1 AND 30),
    CONSTRAINT ck_level_policies_min_total_xp
        CHECK (min_total_xp >= 0)
);

CREATE UNIQUE INDEX uq_level_policies_min_total_xp
    ON learning_service.level_policies (min_total_xp);

CREATE TABLE learning_service.quest_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(100) NOT NULL,
    target_count INTEGER NOT NULL,
    reward_xp BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL,

    CONSTRAINT uq_quest_templates_code
        UNIQUE (code),
    CONSTRAINT ck_quest_templates_type
        CHECK (type IN ('ROUTINE', 'LLM')),
    CONSTRAINT ck_quest_templates_target_count
        CHECK (target_count > 0),
    CONSTRAINT ck_quest_templates_reward_xp
        CHECK (reward_xp > 0)
);

CREATE TABLE learning_service.user_daily_quests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    quest_date DATE NOT NULL,
    template_id BIGINT,
    type VARCHAR(20) NOT NULL,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(100) NOT NULL,
    target_count INTEGER NOT NULL,
    progress_count INTEGER NOT NULL DEFAULT 0,
    reward_xp BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    completed_at TIMESTAMPTZ,
    claimed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version SMALLINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_user_daily_quests_template
        FOREIGN KEY (template_id)
        REFERENCES learning_service.quest_templates (id),
    CONSTRAINT uq_user_daily_quests_user_date_code
        UNIQUE (user_id, quest_date, code),
    CONSTRAINT ck_user_daily_quests_type
        CHECK (type IN ('ROUTINE', 'LLM')),
    CONSTRAINT ck_user_daily_quests_status
        CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'CLAIMED', 'EXPIRED')),
    CONSTRAINT ck_user_daily_quests_target_count
        CHECK (target_count > 0),
    CONSTRAINT ck_user_daily_quests_progress_count
        CHECK (progress_count BETWEEN 0 AND target_count),
    CONSTRAINT ck_user_daily_quests_reward_xp
        CHECK (reward_xp > 0),
    CONSTRAINT ck_user_daily_quests_claimed
        CHECK (claimed_at IS NULL OR status = 'CLAIMED'),
    CONSTRAINT ck_user_daily_quests_version
        CHECK (version >= 0)
);

CREATE INDEX ix_user_daily_quests_user_date
    ON learning_service.user_daily_quests (user_id, quest_date DESC);

CREATE INDEX ix_user_daily_quests_template
    ON learning_service.user_daily_quests (template_id);

CREATE TABLE learning_service.xp_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    user_character_id BIGINT NOT NULL,
    source_type VARCHAR(30) NOT NULL,
    source_id BIGINT NOT NULL,
    amount BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_xp_transactions_user_character
        FOREIGN KEY (user_character_id)
        REFERENCES learning_service.user_characters (id),
    CONSTRAINT uq_xp_transactions_source
        UNIQUE (source_type, source_id),
    CONSTRAINT ck_xp_transactions_source_type
        CHECK (source_type IN ('DAILY_QUEST')),
    CONSTRAINT ck_xp_transactions_amount
        CHECK (amount > 0)
);

CREATE INDEX ix_xp_transactions_character
    ON learning_service.xp_transactions (user_character_id, created_at DESC);

CREATE TABLE learning_service.advancement_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_character_id BIGINT NOT NULL,
    stage VARCHAR(20) NOT NULL,
    level INTEGER NOT NULL,
    xp_transaction_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_advancement_histories_character
        FOREIGN KEY (user_character_id)
        REFERENCES learning_service.user_characters (id),
    CONSTRAINT fk_advancement_histories_transaction
        FOREIGN KEY (xp_transaction_id)
        REFERENCES learning_service.xp_transactions (id),
    CONSTRAINT uq_advancement_histories_character_stage
        UNIQUE (user_character_id, stage),
    CONSTRAINT ck_advancement_histories_stage
        CHECK (stage IN ('FIRST', 'SECOND', 'THIRD')),
    CONSTRAINT ck_advancement_histories_level
        CHECK (level IN (10, 20, 30))
);

CREATE INDEX ix_advancement_histories_xp_transaction
    ON learning_service.advancement_histories (xp_transaction_id);

INSERT INTO learning_service.level_policies (level, min_total_xp)
SELECT level, (level - 1) * (level - 1) * 100
FROM generate_series(1, 30) AS level;

INSERT INTO learning_service.game_characters (name, code, description) VALUES
    ('야간반', 'NIGHT_CLASS', NULL);

INSERT INTO learning_service.quest_templates (
    type,
    code,
    title,
    target_count,
    reward_xp,
    display_order
) VALUES
    ('ROUTINE', 'ATTENDANCE', '출석하기', 1, 20, 1),
    ('ROUTINE', 'STUDY_COMPLETED', '학습 완료하기', 1, 30, 2),
    ('ROUTINE', 'CHARACTER_CHECKED', '캐릭터 확인하기', 1, 10, 3),
    ('ROUTINE', 'ROUTINE_REVIEW', '오늘 학습 돌아보기', 1, 20, 4),
    ('LLM', 'LLM_QUEST', 'AI 추천 퀘스트', 1, 40, 5);
