CREATE TABLE learning_service.community_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    author_user_id UUID NOT NULL,
    scope VARCHAR(20) NOT NULL,
    cohort_id BIGINT,
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT fk_community_posts_cohort
        FOREIGN KEY (cohort_id)
        REFERENCES learning_service.cohorts (id),
    CONSTRAINT ck_community_posts_type
        CHECK (type IN ('NOTICE', 'FREE')),
    CONSTRAINT ck_community_posts_scope
        CHECK (scope IN ('GLOBAL', 'COHORT')),
    CONSTRAINT ck_community_posts_scope_cohort
        CHECK (
            (scope = 'GLOBAL' AND cohort_id IS NULL)
            OR (scope = 'COHORT' AND cohort_id IS NOT NULL)
        ),
    CONSTRAINT ck_community_posts_title
        CHECK (title = BTRIM(title) AND char_length(title) BETWEEN 1 AND 100),
    CONSTRAINT ck_community_posts_content
        CHECK (char_length(BTRIM(content)) BETWEEN 1 AND 10000)
);

CREATE INDEX ix_community_posts_visible_list
    ON learning_service.community_posts (
        scope,
        cohort_id,
        type,
        pinned DESC,
        created_at DESC,
        id DESC
    )
    WHERE deleted_at IS NULL;

CREATE INDEX ix_community_posts_cohort
    ON learning_service.community_posts (cohort_id);

CREATE INDEX ix_community_posts_search
    ON learning_service.community_posts (created_at DESC, id DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE learning_service.community_post_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    storage_key VARCHAR(300) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    display_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_community_post_attachments_post
        FOREIGN KEY (post_id)
        REFERENCES learning_service.community_posts (id)
        ON DELETE CASCADE,
    CONSTRAINT uq_community_post_attachments_storage_key
        UNIQUE (storage_key),
    CONSTRAINT ck_community_post_attachments_storage_key
        CHECK (
            storage_key = BTRIM(storage_key)
            AND storage_key NOT LIKE '/%'
            AND storage_key NOT LIKE '%..%'
            AND char_length(storage_key) BETWEEN 1 AND 300
        ),
    CONSTRAINT ck_community_post_attachments_original_file_name
        CHECK (
            original_file_name = BTRIM(original_file_name)
            AND original_file_name NOT LIKE '%/%'
            AND original_file_name NOT LIKE '%\\%'
            AND original_file_name NOT LIKE '%..%'
            AND char_length(original_file_name) BETWEEN 1 AND 255
        ),
    CONSTRAINT ck_community_post_attachments_content_type
        CHECK (content_type IN ('image/jpeg', 'image/png', 'image/gif')),
    CONSTRAINT ck_community_post_attachments_size
        CHECK (size_bytes > 0),
    CONSTRAINT ck_community_post_attachments_display_order
        CHECK (display_order >= 0)
);

CREATE INDEX ix_community_post_attachments_post_order
    ON learning_service.community_post_attachments (post_id, display_order, id);
