-- 센서 기기 마스터. device_eui 는 LoRaWAN 장치 식별자로 자연키다.
-- space_id 는 미배치 장비를 허용하므로 NULL 가능, 공간 삭제 시 SET NULL.
CREATE TABLE learning_service.sensor_devices (
     device_eui VARCHAR(32) PRIMARY KEY,
     space_id BIGINT,
     model VARCHAR(32) NOT NULL,
     display_name VARCHAR(64),
     installation_point VARCHAR(64),
     expected_interval_seconds INTEGER NOT NULL,
     active BOOLEAN NOT NULL DEFAULT TRUE,
     installed_at TIMESTAMPTZ,
     created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

     CONSTRAINT fk_sensor_devices_space
         FOREIGN KEY (space_id)
             REFERENCES learning_service.spaces (id)
             ON DELETE SET NULL,
     CONSTRAINT ck_sensor_devices_interval
         CHECK (expected_interval_seconds > 0)
);

CREATE INDEX ix_sensor_devices_space ON learning_service.sensor_devices (space_id);

-- 장치·측정 항목당 활성 룰은 하나다 (부분 유니크가 아니라 전체 유니크 — 소프트 삭제 없음).
-- Rule Engine 은 이 테이블에 직접 연결하지 않고 기동 시 REST 로 조회한 뒤
-- 인메모리 RuleCache 로만 운용하며, 변경은 RabbitMQ(rule.updated) 구독으로 갱신한다.
--
-- 장치 삭제 시 CASCADE 하지 않는다. 룰에 이력이 매달려 있어 캐스케이드가
-- 이력 FK 에 막히기 때문이며, 장치 회수는 active = FALSE 로 처리한다.
--
-- version 은 JPA 낙관적 락(@Version)이 관리한다. Hibernate 가 신규 행의 버전을
-- 0 으로 시드하므로 CHECK 는 1 이상이 아니라 0 이상이다.
CREATE TABLE learning_service.threshold_rules (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      device_eui VARCHAR(32) NOT NULL,
      metric VARCHAR(32) NOT NULL,
      operator VARCHAR(8) NOT NULL,
      threshold DOUBLE PRECISION NOT NULL,
      version BIGINT NOT NULL DEFAULT 0,
      created_by_user_id UUID,
      updated_by_user_id UUID,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_threshold_rules_device
          FOREIGN KEY (device_eui)
              REFERENCES learning_service.sensor_devices (device_eui),
      CONSTRAINT uq_threshold_rules_device_metric
          UNIQUE (device_eui, metric),
      -- Rule Engine 이 SensorReading.measurement 와 문자열 완전 일치로 매칭하므로
      -- 대소문자·공백이 섞이면 룰이 조용히 미적중한다. 저장 시점에 원천 차단한다.
      CONSTRAINT ck_threshold_rules_metric
          CHECK (metric = LOWER(BTRIM(metric)) AND metric <> ''),
      CONSTRAINT ck_threshold_rules_operator
          CHECK (operator IN ('GT', 'GTE', 'LT', 'LTE')),
      CONSTRAINT ck_threshold_rules_version
          CHECK (version >= 0)
);

-- 룰 변경 이력. append-only 이므로 (rule_id, rule_version) 이 유일하다.
-- previous_operator / previous_threshold 는 의도적으로 두지 않는다 —
-- 직전 rule_version 행의 next_* 에서 파생 가능한 중복이라 필요 시 LAG 로 조회한다.
--
-- version 갱신과 이 테이블의 INSERT 는 반드시 같은 트랜잭션으로 묶는다.
-- 트리거를 쓰지 않으므로 이 정합성은 전적으로 애플리케이션 코드 책임이다.
CREATE TABLE learning_service.threshold_rule_histories (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       rule_id BIGINT NOT NULL,
       rule_version BIGINT NOT NULL,
       change_type VARCHAR(20) NOT NULL,
       next_operator VARCHAR(8) NOT NULL,
       next_threshold DOUBLE PRECISION NOT NULL,
       changed_by_user_id UUID,
       request_id VARCHAR(100),
       changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

       -- 룰 삭제 경로가 없으므로 CASCADE 하지 않는다.
       -- 이력이 남아 있는 룰의 삭제를 이 FK 가 그대로 막아준다.
       CONSTRAINT fk_threshold_rule_history_rule
           FOREIGN KEY (rule_id)
               REFERENCES learning_service.threshold_rules (id),
       CONSTRAINT ck_threshold_rule_history_change_type
           CHECK (change_type IN ('CREATED', 'UPDATED')),
       -- threshold_rules.version 과 같은 시드(0)를 공유한다.
       CONSTRAINT ck_threshold_rule_history_version
           CHECK (rule_version >= 0),
       CONSTRAINT ck_threshold_rule_history_next_operator
           CHECK (next_operator IN ('GT', 'GTE', 'LT', 'LTE')),
       -- 버전당 이력 행이 정확히 하나만 존재하도록 보장한다.
       CONSTRAINT uq_threshold_rule_history_version
           UNIQUE (rule_id, rule_version)
);

-- "이 룰의 최근 변경 이력부터 조회" 패턴 최적화.
CREATE INDEX idx_threshold_rule_history_time
    ON learning_service.threshold_rule_histories (rule_id, changed_at DESC);

-- 센서 기기 시드
--
-- learning-service 는 센서를 등록하지 않는다. 물리 장비는 외부에서 설치·프로비저닝되며,
-- 임계치 룰이 device_eui 를 FK 로 참조하므로 룰 등록 전에 장비 목록이 존재해야 전제된다.
--
-- 아래 값은 MQTT 실측 관측 결과다. device_eui 는 관측 표에서 생략된 공통 접두사
-- '24e124' 를 복원한 16자리 전체 값이다.
--
-- space_id 는 전부 NULL 이다 (의도).
-- 공간 시드(V8)의 명칭이 아직 예시 단계라 이름으로 묶으면 임시 데이터에 종속되고,
-- 불일치 시 에러가 아니라 조용히 NULL 이 들어가 실패를 놓친다.
-- 센서-공간 배치는 공간 명칭 확정 후 UPDATE 로 처리한다.
--
-- expected_interval_seconds 는 관측 중앙값이 아니라 그 값이 수렴하는 공칭 주기를 쓴다.
-- (121.8 -> 120, 599.9 -> 600). 관측값의 소수점 편차는 장비 드리프트다.

INSERT INTO learning_service.sensor_devices
    (device_eui, space_id, model, display_name, installation_point, expected_interval_seconds, active)
VALUES
    -- 주기형 장비 --------------------------------------------------------------
    ('24e124126d152862', NULL, 'EM500-CO2', '실습실 CO2 센서',   '후방 오른쪽',        120, TRUE),
    ('24e124128c140101', NULL, 'AM107',     '실습실 환경 센서',   '전방 우측',          600, TRUE),
    ('24e124136d151836', NULL, 'EM300-TH',  '사무실 밖 온습도',   '입구 오른쪽',         60, TRUE),
    ('24e124725d081175', NULL, 'AM103',     '사무실 환경 센서',   '업무 공간 안쪽',      60, TRUE),
    ('24e124725d089152', NULL, 'AM103',     '회의실 환경 센서',   NULL,                 600, TRUE),
    ('24e124785c389010', NULL, 'EM320-TH',  '사무실 온습도',      '사무공간 스위치 옆',   60, TRUE),

    -- 이벤트형 장비 ------------------------------------------------------------
    -- door 센서는 개폐 시점에만 발신하므로 고정 주기가 없다. 관측 최대 공백이
    -- 각각 1071.5초, 2144.5초였어서 그보다 여유 있는 3600 을 둔다.
    -- 이 값은 "이 시간을 넘기면 이상"이라는 상한이지 예상 주기가 아니다.
    ('24e124141d180806', NULL, 'WS301',     '실습실 앞문 도어',   '앞문',              3600, TRUE),
    ('24e124141d189196', NULL, 'WS301',     '사무실 출입문 도어', '출입문',             3600, TRUE)
ON CONFLICT DO NOTHING;

-- 무응답 장비(126d152590 / 128c067999)는 의도적으로 제외했다.
-- 유입이 0건이라 모델·주기를 관측으로 확정할 수 없어, 추측값을 정본에 넣는 대신
-- 응답이 확인된 시점에 별도 마이그레이션으로 추가한다.

-- 시드가 실제로 적재됐는지 배포 시점에 확인한다.
DO $$
DECLARE
    seeded INTEGER;
BEGIN
    SELECT count(*) INTO seeded
    FROM learning_service.sensor_devices
    WHERE device_eui LIKE '24e124%';

    IF seeded < 8 THEN
        RAISE EXCEPTION '센서 시드 적재 실패: 기대 8건, 실제 %건', seeded;
    END IF;
END
$$;
